        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 22 18:51:17 2015
        MODULE CKABS__genmod
          INTERFACE 
            SUBROUTINE CKABS
            END SUBROUTINE CKABS
          END INTERFACE 
        END MODULE CKABS__genmod
