        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 22 18:51:18 2015
        MODULE CKPHAZ__genmod
          INTERFACE 
            SUBROUTINE CKPHAZ(ICKWRK,RCKWRK,KPHASE)
              INTEGER(KIND=4) :: ICKWRK(*)
              REAL(KIND=8) :: RCKWRK(*)
              INTEGER(KIND=4) :: KPHASE(*)
            END SUBROUTINE CKPHAZ
          END INTERFACE 
        END MODULE CKPHAZ__genmod
