        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 22 18:51:22 2015
        MODULE MCINIT__genmod
          INTERFACE 
            SUBROUTINE MCINIT(LINKMC,LOUT,LENIMC,LENRMC,IMCWRK,RMCWRK)
              INTEGER(KIND=4) :: LINKMC
              INTEGER(KIND=4) :: LOUT
              INTEGER(KIND=4) :: LENIMC
              INTEGER(KIND=4) :: LENRMC
              INTEGER(KIND=4) :: IMCWRK(*)
              REAL(KIND=8) :: RMCWRK(*)
            END SUBROUTINE MCINIT
          END INTERFACE 
        END MODULE MCINIT__genmod
