        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 22 18:51:24 2015
        MODULE XERPRN__genmod
          INTERFACE 
            SUBROUTINE XERPRN(PREFIX,NPREF,MESSG,NWRAP)
              CHARACTER(*) :: PREFIX
              INTEGER(KIND=4) :: NPREF
              CHARACTER(*) :: MESSG
              INTEGER(KIND=4) :: NWRAP
            END SUBROUTINE XERPRN
          END INTERFACE 
        END MODULE XERPRN__genmod
